### ISSUE TITLE
Day 1 link leads to Day 0

### ISSUE THREAD

**Issue by Sporarum** [scalacenter/scala-advent-of-code#557]
On this page:
https://scalacenter.github.io/scala-advent-of-code/2024/
If you click Day 1, it leads you to
https://scalacenter.github.io/scala-advent-of-code/2024/puzzles/day0
Instead of
https://scalacenter.github.io/scala-advent-of-code/2024/puzzles/day01

It also contains a link to Day 2, which does not exist yet (clicking that leads to Day 1)

And the "Next" link at the end of Day 1 leads to Day 1 2023

I would therefore advise to rename Day 0 to "missing day" with as body something along the lines of "Day X will be available soon/ in Y hours"
The next day which would lead to non-existant days would then point to it

(I tried to do so myself, but couldn't figure it out)

**Comment by bishabosha** [comment]
I believe we should just delete day0

**Comment by bishabosha** [comment]
fixed by #559
